export const environment = {
  production: true,
  defaultLang: 'en',
  supportedLangs: ['en', 'uk', 'ru'],
  contentBasePath: 'assets/content',
  siteName: 'ByByte.DIY STEM School',
  siteUrl: 'https://www.bybyte.diy',
  siteDescription: 'Learn robotics and programming with ByByte.DIY STEM School',
  links: {
    telegram: 'https://t.me/bybytediy',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    discord: 'https://discord.gg/NcfTybwYWq',
    githubOrg: 'https://github.com/ByByte-diy',
    gitMega: 'https://github.com/ByByte-diy/ByByteMega',
    gitNano: 'https://github.com/ByByte-diy/ByByteNano',
    nanoboyBuild: 'https://github.com/ByByte-diy/ByByteNanoBoy',
    nanoBuild: 'platforms/bybyte-nano-assembly-guide.html',
    contributeGuide: 'https://github.com/ByByte-diy/.github/blob/main/CONTRIBUTING.md',
    youtubeChannel: 'https://www.youtube.com/@bybyte-diy',
    youtubeIntroEmbed: 'https://www.youtube.com/embed/9_2A6fj84Rg',
    buildGuide: 'https://docs.bybyte.diy',
    lessons: 'https://github.com/ByByte-diy/ByByteMega/wiki/Lessons',
  },
};
