export const environment = {
  production: false,
  defaultLang: 'en',
  supportedLangs: ['en', 'uk', 'ru'],
  contentBasePath: '/assets/content',
  links: {
    telegram: 'https://t.me',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com',
    discord: 'https://discord.com',
    githubOrg: 'https://github.com/ByByte-diy',
    gitMega: 'https://github.com/ByByte-diy/ByByteMega',
    gitNano: 'https://github.com/ByByte-diy/ByByteNano',
    megaBuild: 'https://github.com/ByByte-diy/ByByteMega',
    nanoBuild: 'https://github.com/ByByte-diy/ByByteNano',
    contributeGuide: 'https://github.com/ByByteDIY/ByByteSite/blob/main/CONTRIBUTING.md',
    youtubeIntroEmbed: 'https://www.youtube.com/embed/vfpC8E4VCk8',
    buildGuide: 'https://github.com/ByByte-diy/ByByteMega/wiki',
    programmingGuide: 'https://github.com/ByByte-diy/ByByteMega/wiki/Programming',
    lessons: 'https://github.com/ByByte-diy/ByByteMega/wiki/Lessons',
  },
};
